FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
COPY src ./src
COPY index.html vite.config.js jsconfig.json tailwind.config.js postcss.config.js ./
RUN npm ci && npm run build

FROM nginx:1.27-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx/frontend.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
